### ISSUE TITLE
Unable getting it work

### ISSUE THREAD

**Issue by havenokarma** [yaegassy/coc-ansible#31]
Hello, Getting error when trying to use extension

```
>>- name: Task name
   $ref '%2F%24defs%2Ftasks' in 'https://raw.githubusercontent.com/ansible/
   ansible-lint/main/src/ansiblelint/schemas/ansible.json' can not be resolved.
   (YAML 768)
```

**Comment by yaegassy** [comment]
Thanks for reporting the issue. I think this is probably an issue on the ansible-lint repository side.

Please report issues to ansible-lint.

https://github.com/ansible/ansible-lint

**Comment by yaegassy** [comment]
I have tried it in my environment. It works fine in my environment and I cannot reproduce the problem.

<img width="551" alt="coc-ansible-issue-31-check-1" src="https://user-images.githubusercontent.com/188642/222449455-67af43f3-d1f1-477f-be15-7bd1424f9b24.png">

Does the problem persist now in your environment?

**Comment by havenokarma** [comment]
Thanks for a quick reply!

**Comment by do3cc** [comment]
I have had the same problem and needed quite some time to find the root cause.
@yaegassy your support in another ticket with the minimum test setup help a lot, thank you!
When I got the error described above, I missed the filemapping from the docs:
```
let g:coc_filetype_map = {
  \ 'yaml.ansible': 'ansible',
  \ }
```
The docs are clear, but I somehow interpreted this as an install another plugin OR do the mapping.
Adding the mapping makes it work.
